#ifndef REGISTRATIONSTATEENUM_H
#define REGISTRATIONSTATEENUM_H

enum class RegistrationState
{
	CURRENTLY_DEREGISTERED = 0,
	PENDING_REGISTRATION = 1,
	CURRENTLY_REGISTERED = 2,
	PENDING_DEREGISTRATION = 3
};

#endif